### ISSUE TITLE
Crop Image

### ISSUE THREAD

**Issue by hongtou820** [iyotetsuya/RectangleDetection#12]
How to crop image, after rectangle detected ?

**Comment by iyotetsuya** [comment]
The rough idea is:
1. get bitmap and the points info when rectangle detected.
2. mapping points to bitmap and creates new bitmap depends on new points.
3. save the bitmap as picture or shows on screen.

**Comment by hongtou820** [comment]
Yes~ i Fund out solution for this~
but i now got other question 
i cannot detect some Light Blue Color rectangle box, with background is white color

**Comment by iyotetsuya** [comment]
in this case, you need to tuning OpenCV function for a more clear edge. 
There's the document may help you get the idea.

https://docs.opencv.org/2.4/doc/tutorials/imgproc/shapedescriptors/find_contours/find_contours.html
https://docs.opencv.org/3.4/d2/d2c/tutorial_sobel_derivatives.html

**Comment by iyotetsuya** [comment]
Issue closed, please reopen it if you have other question.
