### ISSUE TITLE
Error inflating class io.github.iyotetsuya.rectangledetection.views.CameraPreview

### ISSUE THREAD

**Issue by iyotetsuya** [iyotetsuya/RectangleDetection#3]

**Comment by iyotetsuya** [comment]
@Harmeet2491 stacktrace log can't find what problem with it, Did you add other view or code in class/xml? if yes, please post that for more detail, thanks.

**Comment by Harmeet2491** [comment]
I did not add any other code ,I just wanted to see what is the output of your code!

**Comment by iyotetsuya** [comment]
I'm not sure about root cause of this issue, but maybe it can fix. 
[fix_camera_preview_inflating_error](/iyotetsuya/RectangleDetection/tree/feature/fix_camera_preview_inflating_error)

**Comment by Harmeet2491** [comment]
I think I just found it ,camera is depreciated in android 23 so either go ahead with camera2 or downgrade it to 22 ,Thank you for the application,this is somewhat I wanted to do :+1:

**Comment by iyotetsuya** [comment]
That's great~
I will also take this as an enhanced feature to support camera2.
Thank you for your feedback.

**Comment by nikhil4567** [comment]
Hello mates , is there any efficient way where we can improve quality of bitmap we get when rectangle is detected.
And any suggestions  of how to make camera preview  focus when rectangle is detected, so that bitmap is not clear not blurred.
