### ISSUE TITLE
to snap a picture...

### ISSUE THREAD

**Issue by pulkitbjri** [iyotetsuya/RectangleDetection#6]
how to snap a picture when it detects rectrangle..

**Comment by iyotetsuya** [comment]
This link may can give you some idea to do that.
http://stackoverflow.com/questions/2661536/how-to-programmatically-take-a-screenshot-in-android

**Comment by pulkitbjri** [comment]
actually i don't wanna take screenshot!!! when we detect rectangle snap the picture of whole page.....

**Comment by iyotetsuya** [comment]
You have to implement [takePicture](https://developer.android.com/reference/android/hardware/Camera.html#takePicture(android.hardware.Camera.ShutterCallback,%20android.hardware.Camera.PictureCallback,%20android.hardware.Camera.PictureCallback,%20android.hardware.Camera.PictureCallback)) , and draw rectangle into bitmap.

**Comment by iyotetsuya** [comment]
Closing this one, feel free to open a new issue if you have further questions.
