### ISSUE TITLE
Landscape Orientation  Issue

### ISSUE THREAD

**Issue by shyamkumarm** [iyotetsuya/RectangleDetection#8]
Everything works fine in portrait mode, But when i try to change into landscape, The rectangle path is not in accurate position. Any solution ?

**Comment by iyotetsuya** [comment]
The reason is path doesn't rotate with camera raw data,
So you have to map those point to the new coordinate.

**Comment by shyamkumarm** [comment]
so I need to interchange the x and y axis of points to path to draw ???

**Comment by iyotetsuya** [comment]
yep, but don't forget you may have to convert camera coordinates to view coordinates.

**Comment by iyotetsuya** [comment]
Please reopen it if you have additional questions

**Comment by shyamkumarm** [comment]
sure thanks...
