### ISSUE TITLE
Detect the object with custom design

### ISSUE THREAD

**Issue by kiranlanke** [iyotetsuya/RectangleDetection#9]
Thank you for great example. For detecting the object you are using blue color boarder but i want to use some custom design instead of blue boarder. Is there any way to do that?

**Comment by iyotetsuya** [comment]
Depends on what kinds of design you want to use.
but basically, 
https://github.com/iyotetsuya/RectangleDetection/blob/823dc19fce41abad018997957547657cabcb84f5/app/src/main/java/io/github/iyotetsuya/rectangledetection/utils/OpenCVHelper.java#L153
will find 4 points as quadrilateral's vertex,
you have to map those points to your design.
In this project implement, I convert points to quadrilateral's edges,
and use 
https://github.com/iyotetsuya/RectangleDetection/blob/823dc19fce41abad018997957547657cabcb84f5/app/src/main/java/io/github/iyotetsuya/rectangledetection/views/DrawView.java#L41
to draw paths.

**Comment by iyotetsuya** [comment]
Please reopen it if you have additional questions

**Comment by kiranlanke** [comment]
Thank you for your support. I'll get back to you soon...
